// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --------------- //
// onewire_receive //
// --------------- //

#define onewire_receive_wrap_target 2
#define onewire_receive_wrap 8

static const uint16_t onewire_receive_program_instructions[] = {
    0xe580, //  0: set    pindirs, 0             [5] 
    0xa0c3, //  1: mov    isr, null                  
            //     .wrap_target
    0xe027, //  2: set    x, 7                       
    0x3720, //  3: wait   0 pin, 0               [23]
    0x4e01, //  4: in     pins, 1                [14]
    0x0044, //  5: jmp    x--, 4                     
    0x00c8, //  6: jmp    pin, 8                     
    0x0201, //  7: jmp    1                      [2] 
    0x8320, //  8: push   block                  [3] 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program onewire_receive_program = {
    .instructions = onewire_receive_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config onewire_receive_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + onewire_receive_wrap_target, offset + onewire_receive_wrap);
    return c;
}
#endif
